### ISSUE TITLE
DM_API_WS failed to start on linux using dotnet

### ISSUE THREAD

**Issue by chian-007** [SDMXISTATTOOLKIT/META-DATA.MANAGER#1]
hi,there:

I tried to deploy the ISTAT on Linux but DM_API_WS failed due to the backslash of the rules.xml:

Apr 13 22:47:00 iis dotnet-DM_API_WS[10265]: Application startup exception
Apr 13 22:47:00 iis dotnet-DM_API_WS[10265]: System.IO.FileNotFoundException: /var/www/DM_API_WS\config\rules.xml
Apr 13 22:47:00 iis dotnet-DM_API_WS[10265]: at AuthCore.PolicyModuleCore.Manager.PolicyDecisionPointManager..ctor(IHostingEnvironment env, ISTLogger logger) in \\titano\Progetti\SistanHub\Rilasci\pacchetti codice\MDM_V1.5.1_02-12-2020\main\source\server\DM API WS\AuthDBCore\PolicyModuleCore\Manager\PolicyDecisionPointManager.cs:line 46
Apr 13 22:47:00 iis dotnet-DM_API_WS[10265]: at AuthCore.AuthMiddleware..ctor(RequestDelegate next, IOptionsMonitor`1 config, IHostingEnvironment env) in \\titano\Progetti\SistanHub\Rilasci\pacchetti codice\MDM_V1.5.1_02-12-2020\main\source\server\DM API WS\AuthDBCore\AuthMiddleware.cs:line 29
Apr 13 22:47:00 iis dotnet-DM_API_WS[10265]: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

So is  it posssible to use path.combine instead of hardcoding the path.

Thanks,

**Comment by frapercan** [comment]
if you manage to deploy this on linux you are my new God.

**Comment by enprava** [comment]
Hi, did you manage to deploy this on linux?
