### ISSUE TITLE
Unable to Install the version 1.7.3 with SQL Express

### ISSUE THREAD

**Issue by frapercan** [SDMXISTATTOOLKIT/META-DATA.MANAGER#2]
MSDB initialization is failing, I have experience installing previous versions on different machines and with different configurations, but this one is proving impossible.

We want to install it from scratch, no upgrading previous versions.

We have reached the following error after clicking on initialize MSDB in the DM API:

```
2022-07-05 12:52:00,399|[45]|ERROR|DESKTOP-KLB1Q7M|(null)|Estat.Sri.MappingStoreRetrieval.Manager.Database|admin|While ExecuteNonQuery|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IF'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stat

eObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Estat.Sri.MappingStoreRetrieval.Manager.DatabaseTransactional.ExecuteNonQuery(DbCommand command)
   at Estat.Sri.MappingStoreRetrieval.Manager.DatabaseWithLogger.ExecuteNonQuery(DbCommand command)
   at Estat.Sri.MappingStoreRetrieval.Manager.Database.ExecuteNonQuery(String sqlStatement, IList`1 parameters)
ClientConnectionId:669e3a15-d60e-4dfa-adb6-c0ac8af848a7
Error Number:156,State:1,Class:15
```
[conf_files.zip](https://github.com/SDMXISTATTOOLKIT/META-DATA.MANAGER/files/9045832/conf_files.zip)

**Comment by frapercan** [comment]
In the end, we used 1.72 version that was provided to us by Francesco Rizzo Months ago; we just replaced the client. 

It was impossible to use the version from the repo for us (Clean install with 6.0 dotnet).
